apiVersion: v2
name: blobstore-nats
description: HTTP-based blobstore demo backed by NATS

type: application
version: 0.1.0
appVersion: "0.1.0"

kubeVersion: ">= 1.29.0-0"

icon: https://avatars.githubusercontent.com/u/80437882
sources:
  - https://github.com/cosmonic

maintainers:
  - name: Cosmonic
    url: https://github.com/orgs/cosmonic