# For the 'http-trigger' helm chart
components:
  - name: hono-swagger-ui
    image: ghcr.io/cosmonic-labs/control-demos/hono-swagger-ui:0.1.2

ingress:
  host: "hono-swagger-ui.localhost.cosmonic.sh"

hostInterfaces:
  - namespace: wasi
    package: config
    version: 0.2.0-rc.1
    interfaces:
      - store
  - namespace: wasi
    package: logging
    version: 0.1.0-draft
    interfaces:
      - logging

pathNote: "/ui"
