# Default values for http-sample.

# This is to override the chart name.
nameOverride: "" 
fullnameOverride: ""

# Namespace for deployment.
namespace:
  name: default

# This is for setting up a WebAssembly component. 
# More information can be found here: https://cosmonic.com/docs/api-reference/runtime.wasmcloud.dev#component
component:
  name: http-sample
  image: ghcr.io/cosmonic-labs/components/http-sample:0.1.0
  hostname: "localhost:9091"
  hostgroup: "default"
  concurrency: 100
  replicas: 1
  # Custom config key-value pairs specific to the component
  config: {}

# HTTP Provider in Cosmonic Control cosmonic-system namespace.
# From the cosmonic-control-hostgroup chart with http.enabled=true
# More information can be found here: https://cosmonic.com/docs/api-reference/runtime.wasmcloud.dev#provider
httpProvider:
  hostgroup: default
  namespace: cosmonic-system