# For the 'http-trigger' helm chart
components:
  - name: http-server
    image: ghcr.io/cosmonic-labs/components/http-server:0.1.0

ingress:
  host: "http-server.localhost.cosmonic.sh"

hostInterfaces:
  - namespace: wasi
    package: config
    version: 0.2.0-rc.1
    interfaces:
      - store
  - namespace: wasi
    package: logging
    version: 0.1.0-draft
    interfaces:
      - logging
