# For the 'http-trigger' helm chart
components:
  - name: welcome-tour
    image: ghcr.io/cosmonic-labs/components/welcome-tour:0.1.0
    localResources:
      environment:
        config:
          consolehost: "http://localhost"
          consoleport: "8080"

ingress:
  host: "welcome-tour.localhost.cosmonic.sh"

hostInterfaces:
  - namespace: wasi
    package: logging
    version: 0.1.0-draft
    interfaces:
      - logging
  - namespace: wasi
    package: config
    version: 0.2.0-rc.1
    interfaces:
      - store
